### ISSUE TITLE
Lizmap Web Client

### ISSUE THREAD

**Issue by josemvm** [jelix/ldapdao-module#1]
hi Laurent Jouanneau,

have you tried your plugin with LWC?

so please what is really wrong with this: https://github.com/3liz/lizmap-web-client/issues/110 ?

**Comment by laurentj** [comment]
Yes, we have already install it on a customer server

**Comment by laurentj** [comment]
I will verify that everything is in the sources

**Comment by josemvm** [comment]
ok, thanks for your attention

**Comment by laurentj** [comment]
everything is in the repo. Issues are about configurations
