### ISSUE TITLE
Plusieurs groupes LDAP

### ISSUE THREAD

**Issue by maelBL** [jelix/ldapdao-module#2]
Hello,

Dans le cas où un user de l'AD aurait plusieurs groupes, comment ferait-on pour gérer ça ? Car à l'état actuel, le plugin d'authentification récupère uniquement le premier groupe d'un user (propriété memberOf dans mon cas). Mais il est rare qu'un user ne fasse partit que d'un seul groupe, surtout dans un cadre d'entreprise.

Dois-je modifier ce plugin pour l'adapter à mes propres besoins ? Devrais-je effectuer des traitements externes au plugin pour gérer les groupes de l'AD ?

Une modification qui me semblerait plutôt logique serait déjà de rechercher tous les groupes d'un user et non pas le premier enregistrement comme c'est le cas actuellement.

**Comment by maelBL** [comment]
Ayant adopté une structure un peu particulière de la gestion des utilisateurs (authentification via Ldap et stockage d'utilisateurs en base pour pouvoir gérer des préférences), j'ai modifié le fichier à ma façon afin d'en faire un plugin propre à mon cas finalement.

Cependant, je pense qu'il serait toujours intéressant de récupérer tous les groupes du Ldap dans la méthode `verifyPassword($login, $password)`.

**Comment by laurentj** [comment]
Je vais voir ce qu'on peut faire.

N'hésite pas à faire une Pull Request pour proposer des améliorations
