### ISSUE TITLE
LDAP connections over SSL

### ISSUE THREAD

**Issue by vherreros** [jelix/ldapdao-module#5]
Hello,

I'm using LDAPDAO on my LizMap web client environment, and I'm suspecting that LDAPDAO uses by default ldap connections, but not ldaps ones. Though I specifiy the use of secure port 636 in my client, I have no idea on how to tell it to use ldaps protocol.

Is there a way to configure LDAPDAO to use ldaps instead of ldap connections?

Thanks in advance.

P.S.: I'm not allowed to use unsecure port 389 ldap connections in my system.

**Comment by laurentj** [comment]
Hi @vherreros ,

To connect to ldap with ssl, try `hostname=ldaps://my.ldap.server.hostname/`.

See http://php.net/manual/en/function.ldap-connect.php .
